-- Repository-derived PostgreSQL baseline for fresh databases only.
--
-- Source: the nine JPA entities tracked in this repository, rendered with
-- Hibernate ORM 6.6.5.Final and Spring's camel-case-to-underscores naming.
-- This is not an authoritative dump of any deployed environment. Do not run it
-- on a non-empty database and do not mark an existing schema as V1 until the
-- reconciliation and preflight process in this directory's README is complete.

CREATE TABLE food_entries (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    entry_hash varchar(255),
    meal_type varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    quantity float(53) NOT NULL,
    unit varchar(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    food_log_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE food_logs (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    log_date date NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_food_logs_user_date UNIQUE (user_id, log_date)
);

CREATE TABLE habit_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    completion_time varchar(255),
    entry_date date,
    habit_id varchar(255),
    rescheduled_time timestamp(6),
    status varchar(255) NOT NULL
        CHECK (status IN ('COMPLETED', 'MISSED', 'PENDING', 'RESCHEDULED')),
    user_id varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE habits (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    reminder_time time(6) NOT NULL,
    reminder_type varchar(255) NOT NULL,
    repeat_days varchar(255) array NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE nutrition_cache (
    entry_hash varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    payload jsonb NOT NULL,
    PRIMARY KEY (entry_hash)
);

CREATE TABLE nutrition_details (
    id uuid NOT NULL,
    api_response text,
    calories numeric(38, 2),
    carbs_g numeric(38, 2),
    enriched_at timestamp(6) with time zone,
    enrichment_error text,
    enrichment_status varchar(255) NOT NULL,
    fats_g numeric(38, 2),
    fiber_g numeric(38, 2),
    protein_g numeric(38, 2),
    retry_count integer NOT NULL,
    sodium_mg numeric(38, 2),
    sugar_g numeric(38, 2),
    updated_at timestamp(6) with time zone NOT NULL,
    food_entry_id uuid NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE user_nutrient_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    avoided_foods varchar(1024),
    custom_target float(53),
    nutrient_id varchar(255) NOT NULL,
    pinned boolean NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, nutrient_id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    age varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    enabled boolean NOT NULL,
    gender varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE voice_meal_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    completed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    log_date date,
    raw_transcript text,
    status varchar(255) NOT NULL
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE food_entries
    ADD CONSTRAINT FKaui45uoguu5tlr7mbm3waey59
    FOREIGN KEY (food_log_id) REFERENCES food_logs;

ALTER TABLE habits
    ADD CONSTRAINT FKg3n2qqwmsyv3517xdcosouk9i
    FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE nutrition_details
    ADD CONSTRAINT FKpim4idmn0xkrkx9f01d7oink4
    FOREIGN KEY (food_entry_id) REFERENCES food_entries;

ALTER TABLE voice_meal_sessions
    ADD CONSTRAINT FK32xhmorup2wi7ck9rp106lnnv
    FOREIGN KEY (user_id) REFERENCES users;
